CRUD/CRUD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

CRUD/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update', views.update,  name='update'),
    path('<int:pk>/delete', views.delete,  name='delete'),
    path('<int:movie_pk>/comments/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
    path('<int:movie_pk>/comment_create/', views.comment_create, name='comment_create'),
]

CRUD/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=1000)
    title_en = models.CharField(max_length=1000)
    audience = models.IntegerField()
    open_date = models.DateField()
    genre = models.CharField(max_length=100)
    watch_grade = models.CharField(max_length=100)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()

# comments
class Comment(models.Model):
    content = models.TextField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    

CRUD/movies/forms.py
from django import forms
from .models import Movie, Comment

class MovieForm(forms.ModelForm):
    title = forms.CharField(
        label='영화명',
        widget=forms.TextInput(
            attrs={
                'class': 'my-movie',
            }
        )        
    )
    title_en = forms.CharField(
        label='영화명(영문)',
        widget=forms.TextInput(
            attrs={
                'class': 'my-movie',
            }
        )
    )
    audience = forms.IntegerField(
        label='누적 관객수'
    )
    open_date = forms.DateField(
        label='개봉일'
    )
    genre = forms.CharField(
        label='장르'
    )
    watch_grade = forms.CharField(
        label='관람등급'
    )
    score = forms.FloatField(
        label='평점'
    )
    poster_url = forms.CharField(
        label='포스터 이미지 URL'
    )
    description = forms.CharField(
        label='영화 소개',
        widget=forms.Textarea(
            attrs={
                'class': ''                
            }
        )
    )


    class Meta:
        model = Movie
        fields = '__all__'


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('content',)

CRUD/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie, Comment
from .forms import MovieForm, CommentForm
from django.views.decorators.http import require_POST

# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies':movies,
    }
    return render(request, 'movies/index.html', context)


def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()
    context = {
        'form': form,
    }
    return render(request, 'movies/create.html', context)

def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    comments = movie.comment_set.all()
    form = CommentForm()
    context = {
        'movie': movie,
        'comments': comments,
        'form': form,
    }
    return render(request, 'movies/detail.html', context)


def update(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid:
            form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'form': form,
    }
    return render(request, 'movies/update.html', context)

@require_POST
def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()
    return redirect('movies:index')

# deleting comment ... only POST
@require_POST
def comment_delete(request, movie_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect('movies:detail', movie_pk)

# creating comment ... movie_pk is specified
@require_POST
def comment_create(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    # content = request.POST.get('content')
    # Comment.objects.create(content=content, movie=movie)
    form = CommentForm(request.POST)
    print(form) # html 문서임을 확인할 수 있다.
    # <tr><th><label for="id_content">Content:</label></th><td>
    # <textarea name="content" cols="40" rows="10" required id="id_content">
    # 111</textarea></td></tr>
    if form.is_valid():
        comment = form.save(commit=False)     
        comment.movie = movie
        comment.save()
    return redirect('movies:detail', movie_pk)
    

CRUD/CRUD/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
    <h1>HPHK 종합실습</h1>
    <div class="container">
    {% block content %}
    {% endblock  %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

CRUD/movies/templates/movies/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<h1>CREATE</h1>
<form action="" method ="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons submit='작성하기' %}{% endbuttons %}
</form>
{% endblock  %}

CRUD/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
<h1>DETAIL</h1>
<p>영화명 : {{ movie.title }}</p>
<p>누적 관객수 : {{ movie.audience }}</p>
<p>개봉일 : {{ movie.open_date }}</p>
<p>장르 : {{ movie.genre }}</p>
<p>관람등급 : {{ movie.watch_grade }}</p>
<p>평점 : {{ movie.score }}</p>
<p>포스터 이미지 URL : {{ movie.poster_url }}</p>
<p>영화 소개 : {{ movie.description }}</p>



<a href="{% url 'movies:index' %}"><span class="badge badge-secondary">목록</span></a>
<a href="{% url 'movies:update' movie.pk %}"><span class="badge badge-success">수정</span></a>

<form action="{% url 'movies:delete' movie.pk %}" method="POST">
    {% csrf_token %}
    <button class="btn btn-danger">삭제</button>
</form>
<hr>
<form action="{% url 'movies:comment_create' movie.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}     
    <button class='btn btn-warning'>코멘트작성</button>
</form>
<hr>
<h2>코멘트 보기</h2>
{% for comment in comments %}
   <form action="{% url 'movies:comment_delete' movie.pk comment.pk %}" method="POST" class="form-inline">
        <div class="row">
             <div class="col">{{ comment.content }}</div>       
            {% csrf_token %}
            <button class="btn btn-danger btn-sm">삭제</button>
        </div>
   </form>
{% endfor %}

{% endblock  %}

CRUD/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
<h1>1.영화목록</h1>

<a href="{% url 'movies:create' %}">NEW</a>
<hr>
{% for movie in movies %}
{{ movie.pk }} : {{ movie.title }}  (평점 : {{ movie.score }} )
<a href="{% url 'movies:detail' movie.pk %}">DETAIL</a>
<hr>
{% endfor %}
{% endblock  %}

CRUD/movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
<h1>UPDATE</h1>

<form action="" method='POST'>
    {% csrf_token %}
    {{ form }}
    <button>수정</button>
</form>

{% endblock  %}